In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.simplefilter('ignore')
pd.set_option('display.max_columns', None)
file = r'C:\Users\PythonFiles\PYcharm\amazon_sales\artifacts\data.csv'
file1 = 'SALESDATA.xlsx'

In [104]:
df = pd.read_csv(file)
df.tail()

,Discount Amount,Item,List Price,Sales Amount,Sales Amount Based on List Price,Sales Cost Amount,Sales Margin Amount,Sales Price,Sales Quantity,Year,Month
65276,272.5230,Better Fancy Canned Sardines,39.1545,6540.36,6812.8830,2969.78,3570.58,37.588276,174,2019,Dec
65277,548.2520,Monarch Spaghetti,40.3128,13158.10,13706.3520,6424.27,6733.83,38.700294,340,2019,Dec
65278,26.2588,Moms Cole Slaw,27.3537,630.23,656.4888,421.22,209.01,26.259583,24,2019,Dec
65279,447.6400,Swell Canned Peaches,14.2560,10743.32,11190.9600,6258.02,4485.30,13.685758,785,2019,Dec
65280,15.7200,Walrus Chardonnay,0.3929,377.18,392.9000,340.10,37.08,0.377180,1000,2019,Dec

In [105]:
pd.concat([df, df], ignore_index=True, axis=0)

,Discount Amount,Item,List Price,Sales Amount,Sales Amount Based on List Price,Sales Cost Amount,Sales Margin Amount,Sales Price,Sales Quantity,Year,Month
0,158.0400,Nationeel Salted Pretzels,181.4400,204.84,362.8800,59.73,145.11,102.420000,2,2017,Jan
1,420.9000,Ebony Prepared Salad,966.4400,545.54,966.4400,278.38,267.16,545.540000,1,2017,Jan
2,663.4100,Thresher Spicy Mints,507.7500,859.84,1523.2500,488.68,371.16,286.613333,3,2017,Jan
3,179.4500,Big Time Frozen Cheese Pizza,412.0300,232.58,412.0300,84.23,148.35,232.580000,1,2017,Jan
4,1516.5200,Red Spade Turkey Hot Dogs,1160.7000,1965.58,3482.1000,957.15,1008.43,655.193333,3,2017,Jan
...,...,...,...,...,...,...,...,...,...,...,...
130557,272.5230,Better Fancy Canned Sardines,39.1545,6540.36,6812.8830,2969.78,3570.58,37.588276,174,2019,Dec
130558,548.2520,Monarch Spaghetti,40.3128,13158.10,13706.3520,6424.27,6733.83,38.700294,340,2019,Dec
130559,26.2588,Moms Cole Slaw,27.3537,630.23,656.4888,421.22,209.01,26.259583,24,2019,Dec
130560,447.6400,Swell Canned Peaches,14.2560,10743.32,11190.9600,6258.02,4485.30,13.685758,785,2019,Dec
130561,15.7200,Walrus Chardonnay,0.3929,377.18,392.9000,340.10,37.08,0.377180,1000,2019,Dec